# Generated by Django 2.1.13 on 2019-10-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendientesEnviar',
            fields=[
                ('IDPendienteEnviar', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=10, unique=True)),
                ('NombreCortoCliente', models.CharField(max_length=100)),
                ('NombreCortoProveedor', models.CharField(max_length=100)),
                ('FechaDescarga', models.CharField(max_length=100, null=True)),
                ('Moneda', models.CharField(max_length=10)),
                ('CostoSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Status', models.CharField(max_length=15)),
                ('IsFacturaCliente', models.BooleanField()),
                ('IsFacturaProveedor', models.BooleanField()),
                ('IsEvidenciaFisica', models.BooleanField()),
                ('IsEvidenciaDigital', models.BooleanField()),
            ],
            options={
                'db_table': 'PendientesEnviar',
            },
        ),
        migrations.CreateModel(
            name='RelacionConceptoxProyecto',
            fields=[
                ('RelacionIDConceptoxProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('IDConcepto', models.IntegerField(default=0)),
                ('IDCliente', models.IntegerField(default=0)),
                ('IDProveedor', models.IntegerField(default=0)),
                ('Proyecto', models.CharField(max_length=30)),
                ('IDPendienteEnviar', models.ForeignKey(db_column='IDPendienteEnviar', on_delete=django.db.models.deletion.CASCADE, to='ApiViajes.PendientesEnviar')),
            ],
            options={
                'db_table': 'RelacionConceptoxProyecto',
            },
        ),
    ]
