# Generated by Django 2.1.13 on 2019-10-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendientesEnviar',
            fields=[
                ('IDPendienteEnviar', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=10, unique=True)),
                ('NombreCortoCliente', models.CharField(max_length=100)),
                ('NombreCortoProveedor', models.CharField(max_length=100)),
                ('FechaDescarga', models.CharField(max_length=100)),
                ('Moneda', models.CharField(max_length=10)),
                ('Costo', models.DecimalField(decimal_places=4, max_digits=11)),
                ('CostoSubtotal', models.DecimalField(decimal_places=4, max_digits=11)),
                ('CostoIVA', models.DecimalField(decimal_places=4, max_digits=11)),
                ('CostoRetencion', models.DecimalField(decimal_places=4, max_digits=11)),
                ('CostoTotal', models.DecimalField(decimal_places=4, max_digits=11)),
                ('Precio', models.DecimalField(decimal_places=4, max_digits=11)),
                ('PrecioSubtotal', models.DecimalField(decimal_places=4, max_digits=11)),
                ('PrecioIVA', models.DecimalField(decimal_places=4, max_digits=11)),
                ('PrecioRetencion', models.DecimalField(decimal_places=4, max_digits=11)),
                ('PrecioTotal', models.DecimalField(decimal_places=4, max_digits=11)),
                ('Status', models.CharField(max_length=15)),
                ('IsFacturaCliente', models.BooleanField()),
                ('IsFacturaProveedor', models.BooleanField()),
                ('IsEvidenciaFisica', models.BooleanField()),
                ('IsEvidenciaDigital', models.BooleanField()),
            ],
        ),
    ]
