# Generated by Django 2.1.13 on 2019-10-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiViajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionConceptoxProyecto',
            fields=[
                ('RelacionIDConceptoxProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('IDConcepto', models.IntegerField()),
                ('IDCliente', models.IntegerField()),
                ('IDProveedor', models.IntegerField()),
                ('Proyecto', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='Costo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='CostoIVA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='CostoRetencion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='CostoSubtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='CostoTotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='Precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='PrecioIVA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='PrecioRetencion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='PrecioSubtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='PrecioTotal',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='relacionconceptoxproyecto',
            name='IDPendienteEnviar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiViajes.PendientesEnviar'),
        ),
    ]
