# Generated by Django 2.1.13 on 2019-11-11 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApiViajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientesenviar',
            name='FechaDescarga',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
