# Generated by Django 2.1.13 on 2020-01-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiViajes', '0002_auto_20191216_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientesenviar',
            name='Folio',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
