# Generated by Django 2.1.13 on 2019-10-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiViajes', '0002_auto_20191007_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendientesenviar',
            name='Costo',
        ),
        migrations.RemoveField(
            model_name='pendientesenviar',
            name='Precio',
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='CostoIVA',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='CostoRetencion',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='CostoSubtotal',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='CostoTotal',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='PrecioIVA',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='PrecioRetencion',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='PrecioSubtotal',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='PrecioTotal',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='relacionconceptoxproyecto',
            name='IDCliente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relacionconceptoxproyecto',
            name='IDConcepto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relacionconceptoxproyecto',
            name='IDProveedor',
            field=models.IntegerField(default=0),
        ),
    ]
