# Generated by Django 2.1.13 on 2020-01-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiViajes', '0003_auto_20200102_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendientesenviar',
            name='TipoConcepto',
            field=models.CharField(default='Viaje', max_length=30),
            preserve_default=False,
        ),
    ]
