# Generated by Django 2.1.13 on 2020-01-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiViajes', '0003_auto_20200121_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ext_pendienteenviar_precio',
            name='PrecioServicios',
        ),
        migrations.RemoveField(
            model_name='pendientesenviar',
            name='DiasCredito',
        ),
        migrations.AddField(
            model_name='ext_pendienteenviar_precio',
            name='ServiciosIVA',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='ext_pendienteenviar_precio',
            name='ServiciosRetencion',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='ext_pendienteenviar_precio',
            name='ServiciosSubtotal',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='ext_pendienteenviar_precio',
            name='ServiciosTotal',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pendientesenviar',
            name='IsControlDesk',
            field=models.BooleanField(null=True),
        ),
    ]
