# Generated by Django 2.1.13 on 2019-10-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiViajes', '0003_auto_20191008_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientesenviar',
            name='FechaDescarga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
