# Generated by Django 2.1.13 on 2019-10-28 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiViajes', '0004_auto_20191010_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionconceptoxproyecto',
            name='IDPendienteEnviar',
            field=models.ForeignKey(db_column='IDPendienteEnviar', on_delete=django.db.models.deletion.CASCADE, to='ApiViajes.PendientesEnviar'),
        ),
        migrations.AlterModelTable(
            name='pendientesenviar',
            table='PendientesEnviar',
        ),
        migrations.AlterModelTable(
            name='relacionconceptoxproyecto',
            table='RelacionConceptoxProyecto',
        ),
    ]
