# Generated by Django 2.1.13 on 2020-01-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiViajes', '0004_auto_20200128_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ext_pendienteenviar_precio',
            name='ServiciosIVA',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ext_pendienteenviar_precio',
            name='ServiciosRetencion',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ext_pendienteenviar_precio',
            name='ServiciosSubtotal',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ext_pendienteenviar_precio',
            name='ServiciosTotal',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30, null=True),
        ),
    ]
